### PR TITLE
Rails 6 support

### PR DESCRIPTION
**Pull request by jakedouglas**
So far I've just bumped the versions and added an appraisal.

All of the spec failures look like this:

```
      Failure/Error: set_attribute_was("#{context}_list", taggable_context.persisted_tags.to_s)

      NoMethodError:
        undefined method `set_attribute_was' for #<TaggableModel:0x00007fbc7d240770>
      # ./lib/easy_tags/taggable_methods.rb:70:in `_mark_dirty'
```

This is what ActsAsTaggableOn replaced it with: https://github.com/mbleigh/acts-as-taggable-on/pull/968/files#diff-6fb8d10ba793f1b09e64f2923988ee4e

Here's another random person with something that apparently worked for them: https://github.com/TheRealNeil/acts-as-taggable-on/commit/5458d64d125338f738fe64cb84bcabd741f94a72

No idea if either of these are appropriate here; not familiar with either EasyTags or ActsAsTaggableOn.

@iiwo thoughts on the preferred fix?

### CODE REVIEW

**Comment by iiwo** [comment]
Thanks! I'll look into this. Can you add the `activerecord_6.0.gemfile` to [Travis config](https://github.com/iiwo/easy_tags/blob/master/.travis.yml#L22)?

**Comment by jakedouglas** [comment]
Done :+1:

**Comment by iiwo** [comment]
@jakedouglas I've merged a [fix for the Rails 6 compatibility issue](https://github.com/iiwo/easy_tags/pull/27/files). Thanks for the insight and the links provided - that really helped! Can you rebase to master? Looks like this still needs some small config adjustments and should be good to go - feel free to drop older Ruby/Rails versions with this

**Comment by jakedouglas** [comment]
@iiwo dropped a few to get CI passing and bumped the gem version.

**Comment by iiwo** [comment]
@jakedouglas awesome stuff - merging in

**Pull request merged**
